 
DECLARE @COUNT AS INT=49000
 --TRUNCATE TABLE CUSTOMERS 
DECLARE @NAME AS VARCHAR(100)
DECLARE @SURNAME AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(100)
DECLARE @BIRTHDATE AS DATETIME
DECLARE @CITY AS VARCHAR(100)
DECLARE @TOWN AS VARCHAR(100)
DECLARE @DISTRICT AS VARCHAR(100)
DECLARE @TELNR AS VARCHAR(100)
DECLARE @PHONECODE AS VARCHAR(100)
DECLARE @ID AS INT
DECLARE @I AS INT=0


WHILE @I<@COUNT 
BEGIN

SET @ID=RAND()*(SELECT MAX(ID) FROM NAMES)
SELECT @NAME=NAME_,@GENDER=GENDER FROM NAMES WHERE ID=@ID

SET @ID=RAND()*(SELECT MAX(ID) FROM SURNAMES)
SELECT @SURNAME=SURNAME FROM SURNAMES WHERE ID=@ID 

SET @ID=RAND()*(SELECT MAX(ID) FROM CITY_DISTRICT)
SELECT @CITY=CITY,@TOWN=TOWN,@PHONECODE=PHONECODE  FROM CITY_DISTRICT WHERE ID=@ID 

SET @ID=RAND()*365*60
SET @BIRTHDATE=DATEADD(DAY,@ID,'19400101')

SET @ID=RAND()*(SELECT MAX(ID) FROM TELEPHONES )
SELECT @TELNR=+'('+@PHONECODE+')'+TELNR FROM TELEPHONES WHERE ID=@ID 


INSERT INTO CUSTOMERS (NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN,TELNR)
VALUES (@NAME+' '+@SURNAME, @GENDER, @BIRTHDATE, @CITY, @TOWN,@TELNR )
 SET @I=@I+1
END
