DECLARE @I AS INT=0
WHILE @I<1000
BEGIN
DECLARE @CUSTOMERID AS INT
DECLARE @ORDERID AS INT
DECLARE @ADDRESSID AS INT
DECLARE @DATE AS DATETIME
DECLARE @ITEMCOUNT AS INT
DECLARE @ITEMID AS INT
DECLARE @AMOUNT AS INT
DECLARE @PAYMENTTYPEID AS INT
DECLARE @DELIVERYTYPEID AS INT
 
SELECT @CUSTOMERID=RAND()*1000
SELECT @ADDRESSID=(SELECT TOP 1 ID FROM ADDRESS WHERE CUSTOMERID=@CUSTOMERID)
SET @ITEMCOUNT=  (RAND()*4)+1

DECLARE @MAXFICHENO AS VARCHAR(100)
SELECT @MAXFICHENO=MAX(FICHENO) FROM ORDERFICHE
SET @MAXFICHENO=ISNULL(@MAXFICHENO,'FICHENO000')
DECLARE @MAXFICHENO2 AS INT
SET @MAXFICHENO2=CONVERT(INT,REPLACE(@MAXFICHENO,'FICHENO',''))+1
 

 
SET @DATE=DATEADD(DAY,RAND()*365,'20180101')
SET @DATE=DATEADD(HOUR,RAND()*18,@DATE)
SET @DATE=DATEADD(MINUTE,RAND()*60,@DATE)
SET @DATE=DATEADD(SECOND,RAND()*60,@DATE)

SET @PAYMENTTYPEID=1+(RAND())*2
SET @DELIVERYTYPEID=1+(RAND())*1
 
 INSERT INTO ORDERFICHE( FICHENO, DATE_, CUSTOMERID, ADDRESSID, PAYMENTYPEID, DELIVERYID, TOTALPRICE, TOTALVAT, NETTOTAL)
 SELECT 'FICHENO'+CONVERT(VARCHAR,@MAXFICHENO2), @DATE, @CUSTOMERID, @ADDRESSID, @PAYMENTTYPEID, @DELIVERYTYPEID, 0, 0, 0

 SET @ORDERID=@@IDENTITY
 DECLARE @K AS INT=0
 
 WHILE @K<@ITEMCOUNT

 BEGIN
 SET @ITEMID =CONVERT(INT,RAND()*24)
 SET @AMOUNT=CONVERT(INT,(RAND()*3))+1
 INSERT INTO ORDERLINE_ (ORDERFICHEID,ITEMID,AMOUNT,UNITPRICE,VAT,TOTALPRICE,VATAMOUNT,NETTTOTAL)
 SELECT @ORDERID,ID,@AMOUNT,PRICE,18 AS VAT, @AMOUNT*PRICE AS TOTALPRICE,@AMOUNT*PRICE*0.18,@AMOUNT*PRICE*0.82
 FROM ITEMS  WHERE ID=@ITEMID
 SET @K=@K+1
 
 UPDATE ORDERFICHE SET TOTALPRICE=(SELECT SUM(TOTALPRICE) FROM ORDERLINE_ WHERE ORDERFICHEID=ORDERFICHE.ID)  
 UPDATE ORDERFICHE SET TOTALVAT=(SELECT SUM(VATAMOUNT) FROM ORDERLINE_ WHERE ORDERFICHEID=ORDERFICHE.ID)    
 UPDATE ORDERFICHE SET NETTOTAL=(SELECT SUM(NETTTOTAL) FROM ORDERLINE_ WHERE ORDERFICHEID=ORDERFICHE.ID)  
 END


SET @I=@I+1
END